In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV
import warnings

warnings.filterwarnings("ignore")

df = pd.read_csv(r"C:\Users\jesse\OneDrive\Desktop\churn_clean.csv")

In [2]:
del df["CaseOrder"], df["Customer_id"], df["Interaction"], df["UID"], df["City"], df["State"], df["County"], df["Zip"], df["Lat"], df["Lng"]

In [3]:
del df["Population"], df["Job"], df["TimeZone"]

In [9]:
# Labels are the values we want to predict
y = np.array(df["Churn"])
# Remove the labels from the features
# axis 1 refers to the columns
x = df.drop('Churn', axis = 1)
# Saving feature names for later use
column_names = list(x.columns)

In [11]:
y = pd.get_dummies(y)

x = pd.get_dummies(x)

In [13]:
x = x.replace({True: 1, False: 0})

y = y.replace({True: 1, False: 0})





In [15]:
x = x.apply(pd.to_numeric, errors="coerce")

y = y.apply(pd.to_numeric, errors="coerce")

In [17]:
y = y["Yes"]

In [19]:
cleaned_data = pd.merge(y, x, left_index=True, right_index=True)

In [21]:
cleaned_data.columns = ['Churn_yes', 'Children', 'Age', 'Income', 'Outage_sec_perweek', 'Email', 'Contacts', 'Yearly_equip_failure', 'Tenure', 'MonthlyCharge', 'Bandwidth_GB_Year', 'Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7', 'Item8', 'Area_Rural', 'Area_Suburban', 'Area_Urban', 'Marital_Divorced', 'Marital_Married', 'Marital_Never Married', 'Marital_Separated', 'Marital_Widowed', 'Gender_Female', 'Gender_Male', 'Gender_Nonbinary', 'Techie_No', 'Techie_Yes', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two Year', 'Port_modem_No', 'Port_modem_Yes', 'Tablet_No', 'Tablet_Yes', 'InternetService_DSL', 'InternetService_Fiber Optic', 'Phone_No', 'Phone_Yes', 'Multiple_No', 'Multiple_Yes', 'OnlineSecurity_No', 'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_Yes', 'PaperlessBilling_No', 'PaperlessBilling_Yes', 'PaymentMethod_Bank Transfer(automatic)', 'PaymentMethod_Credit Card (automatic)', 'PaymentMethod_Electronic Check', 'PaymentMethod_Mailed Check']

In [23]:
cleaned_data.to_csv(r"C:\Users\jesse\OneDrive\Desktop\D603 Cleaned Data")

In [25]:
x = np.array(x)

y = np.array(y)

In [27]:
print(y)

[0 1 0 ... 0 0 0]


In [29]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.3)

train_x, valid_x, train_y, valid_y = train_test_split(train_x, train_y, test_size = 0.5)

In [31]:
merge_train_x = pd.DataFrame(train_x)

merge_train_y = pd.DataFrame(train_y)

In [33]:
merge_train_x.columns = ['Children', 'Age', 'Income', 'Outage_sec_perweek', 'Email', 'Contacts', 'Yearly_equip_failure', 'Tenure', 'MonthlyCharge', 'Bandwidth_GB_Year', 'Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7', 'Item8', 'Area_Rural', 'Area_Suburban', 'Area_Urban', 'Marital_Divorced', 'Marital_Married', 'Marital_Never Married', 'Marital_Separated', 'Marital_Widowed', 'Gender_Female', 'Gender_Male', 'Gender_Nonbinary', 'Techie_No', 'Techie_Yes', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two Year', 'Port_modem_No', 'Port_modem_Yes', 'Tablet_No', 'Tablet_Yes', 'InternetService_DSL', 'InternetService_Fiber Optic', 'Phone_No', 'Phone_Yes', 'Multiple_No', 'Multiple_Yes', 'OnlineSecurity_No', 'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_Yes', 'PaperlessBilling_No', 'PaperlessBilling_Yes', 'PaymentMethod_Bank Transfer(automatic)', 'PaymentMethod_Credit Card (automatic)', 'PaymentMethod_Electronic Check', 'PaymentMethod_Mailed Check']

In [34]:
merge_train_y.columns = ['Churn_yes']

In [35]:
training_data = pd.merge(merge_train_y, merge_train_x, left_index=True, right_index=True)

In [36]:
training_data.to_csv(r"C:\Users\jesse\OneDrive\Desktop\D603 Training Data")

In [40]:
merge_test_x = pd.DataFrame(test_x)

merge_test_y = pd.DataFrame(test_y)

merge_test_x.columns = ['Children', 'Age', 'Income', 'Outage_sec_perweek', 'Email', 'Contacts', 'Yearly_equip_failure', 'Tenure', 'MonthlyCharge', 'Bandwidth_GB_Year', 'Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7', 'Item8', 'Area_Rural', 'Area_Suburban', 'Area_Urban', 'Marital_Divorced', 'Marital_Married', 'Marital_Never Married', 'Marital_Separated', 'Marital_Widowed', 'Gender_Female', 'Gender_Male', 'Gender_Nonbinary', 'Techie_No', 'Techie_Yes', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two Year', 'Port_modem_No', 'Port_modem_Yes', 'Tablet_No', 'Tablet_Yes', 'InternetService_DSL', 'InternetService_Fiber Optic', 'Phone_No', 'Phone_Yes', 'Multiple_No', 'Multiple_Yes', 'OnlineSecurity_No', 'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_Yes', 'PaperlessBilling_No', 'PaperlessBilling_Yes', 'PaymentMethod_Bank Transfer(automatic)', 'PaymentMethod_Credit Card (automatic)', 'PaymentMethod_Electronic Check', 'PaymentMethod_Mailed Check']

merge_test_y.columns = ['Churn_yes']
testing_data = pd.merge(merge_test_y, merge_test_x, left_index=True, right_index=True)

testing_data.to_csv(r"C:\Users\jesse\OneDrive\Desktop\D603 Testing Data")

In [43]:
merge_valid_x = pd.DataFrame(valid_x)

merge_valid_y = pd.DataFrame(valid_y)

merge_valid_x.columns = ['Children', 'Age', 'Income', 'Outage_sec_perweek', 'Email', 'Contacts', 'Yearly_equip_failure', 'Tenure', 'MonthlyCharge', 'Bandwidth_GB_Year', 'Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7', 'Item8', 'Area_Rural', 'Area_Suburban', 'Area_Urban', 'Marital_Divorced', 'Marital_Married', 'Marital_Never Married', 'Marital_Separated', 'Marital_Widowed', 'Gender_Female', 'Gender_Male', 'Gender_Nonbinary', 'Techie_No', 'Techie_Yes', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two Year', 'Port_modem_No', 'Port_modem_Yes', 'Tablet_No', 'Tablet_Yes', 'InternetService_DSL', 'InternetService_Fiber Optic', 'Phone_No', 'Phone_Yes', 'Multiple_No', 'Multiple_Yes', 'OnlineSecurity_No', 'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_Yes', 'PaperlessBilling_No', 'PaperlessBilling_Yes', 'PaymentMethod_Bank Transfer(automatic)', 'PaymentMethod_Credit Card (automatic)', 'PaymentMethod_Electronic Check', 'PaymentMethod_Mailed Check']

merge_valid_y.columns = ['Churn_yes']
validation_data = pd.merge(merge_valid_y, merge_valid_x, left_index=True, right_index=True)

validation_data.to_csv(r"C:\Users\jesse\OneDrive\Desktop\D603 Validation Data")

In [45]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 500, random_state = 42)
# Train the model on training data
rf.fit(train_x, train_y);

In [47]:
y_pred = rf.predict(valid_x).round()

In [49]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(valid_y, y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[2790  167]
 [ 283  760]]


In [51]:
from sklearn.metrics import classification_report

print(classification_report(valid_y, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.94      0.93      2957
           1       0.82      0.73      0.77      1043

    accuracy                           0.89      4000
   macro avg       0.86      0.84      0.85      4000
weighted avg       0.88      0.89      0.89      4000



In [53]:
from sklearn.metrics import roc_auc_score 

roc_auc = roc_auc_score(valid_y, y_pred) 
print(roc_auc)

0.8360955737899993


In [55]:
from sklearn.metrics import accuracy_score

print(accuracy_score(valid_y, y_pred))

0.8875


In [57]:
from pprint import pprint

pprint(rf.get_params())

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 500,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}


In [59]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Maximum number of levels in tree
max_leaf_nodes = [20, 50,100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_leaf_nodes': max_leaf_nodes,
               'min_samples_leaf': min_samples_leaf}
pprint(random_grid)

{'max_leaf_nodes': [20, 50, 100],
 'min_samples_leaf': [1, 2, 4],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


In [61]:
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 200, cv = 3, verbose=2, random_state=11, n_jobs = -1)
# Fit the random search model
rf_random.fit(valid_x, valid_y)

Fitting 3 folds for each of 90 candidates, totalling 270 fits


RandomizedSearchCV(cv=3,
                   estimator=RandomForestRegressor(n_estimators=500,
                                                   random_state=42),
                   n_iter=200, n_jobs=-1,
                   param_distributions={'max_leaf_nodes': [20, 50, 100],
                                        'min_samples_leaf': [1, 2, 4],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=11, verbose=2)

In [63]:
rf_random.best_params_

{'n_estimators': 1600, 'min_samples_leaf': 4, 'max_leaf_nodes': 100}

In [65]:
y_pred_test = rf_random.predict(test_x).round()

In [67]:
cm_test = confusion_matrix(test_y, y_pred_test)

print('Confusion matrix\n\n', cm_test)

Confusion matrix

 [[1369   92]
 [ 116  423]]


In [69]:
print(classification_report(test_y, y_pred_test))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93      1461
           1       0.82      0.78      0.80       539

    accuracy                           0.90      2000
   macro avg       0.87      0.86      0.87      2000
weighted avg       0.89      0.90      0.90      2000



In [71]:
roc_auc_test = roc_auc_score(test_y, y_pred_test) 
print(roc_auc_test)

0.8609080369127303


In [73]:
print(accuracy_score(test_y, y_pred_test))

0.896
